export interface NewsItem {
  id: string;
  title: string;
  source: string;
  date: string; // e.g. '24 Aug 2026'
  dateIso: string; // '2026-08-24'
  category: string;
  importance: 'HIGH' | 'NORMAL';
  gsPaper: string;
  summary: string;
  topics: string[];
}

export const ALL_NEWS_ITEMS: NewsItem[] = [
  // ─── 24 Aug 2026 (Today) ─────────────────────────────────
  {
    id: 'news-24-01',
    title: 'PM Modi Concludes Historic Bilateral Visit to Poland & Ukraine; Elevates Strategic Ties',
    source: 'The Hindu',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'GEOPOLITICS',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'First visit by an Indian Prime Minister to Poland in 45 years and Ukraine since 1991. Strategic Partnership agreement signed in Warsaw; high-level discussions held in Kyiv on food security, diplomatic conflict resolution, and defense technology collaboration.',
    topics: ['India-Poland Relations', 'India-Ukraine', 'Diplomacy', 'Strategic Autonomy'],
  },
  {
    id: 'news-24-02',
    title: 'Supreme Court 7-Judge Bench Upholds Sub-Classification of Scheduled Castes for Affirmative Action',
    source: 'The Hindu',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'POLITY',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'By a 6:1 majority, the Supreme Court ruled that State governments possess constitutional power under Articles 14, 15, and 16 to sub-classify Scheduled Castes to provide quota benefits to more backward groups, subject to empirical data.',
    topics: ['Article 14', 'Reservation', 'Affirmative Action', 'Judiciary', 'Social Justice'],
  },
  {
    id: 'news-24-03',
    title: 'DRDO Successfully Completes High-Altitude Desert & Firing Trials for Indigenous "Zorawar" Light Tank',
    source: 'Indian Express',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'DEFENCE',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'The 25-tonne light tank designed specifically for mountain warfare in Eastern Ladakh and Sikkim successfully validated missile firing and amphibious mobility tests. Induction planned by early 2027.',
    topics: ['Zorawar Tank', 'DRDO', 'Indigenisation of Defence', 'LAC Mountain Warfare'],
  },
  {
    id: 'news-24-04',
    title: 'NPCI-UPI Links with UAE\'s AANI and Singapore\'s PayNow for Instant Cross-Border Rupee Settlements',
    source: 'Press Information Bureau',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'ECONOMY',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Reserve Bank of India expands bilateral digital payment corridors enabling real-time low-cost cross-border remittances. Eliminates intermediary correspondent banking fees and enhances rupee internationalisation.',
    topics: ['Digital Public Infrastructure', 'UPI Internationalisation', 'Cross-Border Payments', 'RBI'],
  },
  {
    id: 'news-24-05',
    title: 'National Clean Air Programme (NCAP) 2026 Assessment: 95 Cities Achieve Over 25% Reduction in PM2.5',
    source: 'Indian Express',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'ENVIRONMENT',
    importance: 'NORMAL',
    gsPaper: 'GS-III',
    summary: 'Environment Ministry report indicates major air quality improvements attributed to dust suppression grids, EV transition in public transport, and industrial emission switchover to natural gas.',
    topics: ['NCAP', 'Air Pollution', 'PM2.5', 'Environmental Governance'],
  },
  {
    id: 'news-24-06',
    title: 'Ministry of Mines Releases National Critical Minerals Recycling Policy & Incentive Framework',
    source: 'Hindustan Times',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'SCIENCE_TECH',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Scheme offers 20% capital subsidies for battery and rare-earth element recovery plants. Aims to secure 30% domestic supply of Lithium, Cobalt, and Neodymium through urban mining by 2030.',
    topics: ['Critical Minerals', 'Lithium', 'Rare Earth Elements', 'Circular Economy'],
  },
  {
    id: 'news-24-07',
    title: 'India-ASEAN Free Trade in Goods Agreement (AITIGA) Modernisation Talks Enter Final Round in Jakarta',
    source: 'The Hindu',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'IR',
    importance: 'NORMAL',
    gsPaper: 'GS-II',
    summary: 'Commerce Ministry delegation seeks stricter Rules of Origin (ROO) to curb Chinese circumvention and wider market access for Indian pharmaceutical and IT exports.',
    topics: ['AITIGA', 'Act East Policy', 'ASEAN-India', 'Rules of Origin'],
  },
  {
    id: 'news-24-08',
    title: 'Health Ministry Completes Pan-India Rollout of U-WIN Portal for Universal Child Immunization Tracking',
    source: 'Press Information Bureau',
    date: '24 Aug 2026',
    dateIso: '2026-08-24',
    category: 'GOVERNANCE',
    importance: 'NORMAL',
    gsPaper: 'GS-II',
    summary: 'Modeled after CoWIN, U-WIN digitized records of over 2.9 Crore pregnant women and infants, automating vaccination alerts, QR certificates, and reducing dropout rates under Mission Indradhanush.',
    topics: ['U-WIN', 'Mission Indradhanush', 'E-Health', 'Public Health Governance'],
  },

  // ─── 23 Aug 2026 ─────────────────────────────────────────
  {
    id: 'news-23-01',
    title: 'India-China Bilateral Dialogue on Border Disengagement Advances in Eastern Ladakh',
    source: 'The Hindu',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'GEOPOLITICS',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'Special Representatives met to review diplomatic and military channels for complete disengagement along LAC. India insists on restoration of status quo ante at Depsang and Demchok.',
    topics: ['LAC', 'India-China Relations', 'National Security'],
  },
  {
    id: 'news-23-02',
    title: 'India Semiconductor Mission Approves Phase-II Fabrication Plants in Gujarat & Tamil Nadu',
    source: 'Indian Express',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'SCIENCE_TECH',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Union Cabinet approves ₹45,000 Cr outlay for sub-10nm chip manufacturing and R&D ecosystem. Three fabs to be operational by 2029.',
    topics: ['ISM', 'Make in India', 'Electronics Manufacturing'],
  },
  {
    id: 'news-23-03',
    title: 'Supreme Court Standardizes Guidelines on Preventive Detention under Article 22',
    source: 'Press Information Bureau',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'POLITY',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'Constitution Bench mandates strict adherence to procedural safeguards and 90-day review limits. Personal liberty cannot be curtailed without compelling grounds.',
    topics: ['Article 22', 'Fundamental Rights', 'Judiciary'],
  },
  {
    id: 'news-23-04',
    title: 'RBI Monetary Policy Committee Keeps Repo Rate Unchanged at 6.5% Amid Softening Inflation',
    source: 'The Hindu',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'ECONOMY',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Core CPI inflation stabilized at 3.8% in July. MPC maintains accommodative stance to support growth recovery while keeping inflation within target band.',
    topics: ['RBI', 'Monetary Policy', 'Inflation', 'Interest Rates'],
  },
  {
    id: 'news-23-05',
    title: 'QUAD Summit 2026: Leaders Announce Indo-Pacific Maritime Domain Awareness Initiative',
    source: 'Indian Express',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'IR',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'PM Modi, Presidents Biden, Albanese, and PM Kishida unveil shared satellite-based surveillance to monitor illegal fishing and maritime security threats.',
    topics: ['QUAD', 'Indo-Pacific', 'Maritime Security'],
  },
  {
    id: 'news-23-06',
    title: 'National Education Policy 2020: States Report 85% Implementation of Mother-Tongue Instruction',
    source: 'Hindustan Times',
    date: '23 Aug 2026',
    dateIso: '2026-08-23',
    category: 'GOVERNANCE',
    importance: 'NORMAL',
    gsPaper: 'GS-II',
    summary: 'Education Ministry data shows majority of states have adopted regional language instruction up to Grade 5 under NEP framework.',
    topics: ['NEP 2020', 'Education Reform', 'Multilingual Education'],
  },

  // ─── 22 Aug 2026 ─────────────────────────────────────────
  {
    id: 'news-22-01',
    title: 'Western Ghats Receives UNESCO World Heritage Extension for 39 New Serial Sites',
    source: 'The Hindu',
    date: '22 Aug 2026',
    dateIso: '2026-08-22',
    category: 'ENVIRONMENT',
    importance: 'HIGH',
    gsPaper: 'GS-I',
    summary: 'UNESCO expands Western Ghats heritage designation covering biodiversity hotspots across Kerala, Karnataka and Tamil Nadu. Kasturirangan Committee recommendations partly adopted.',
    topics: ['UNESCO', 'Western Ghats', 'Biodiversity', 'Kasturirangan Report'],
  },
  {
    id: 'news-22-02',
    title: 'ISRO Successfully Tests Reusable Launch Vehicle RLV-TD X3 from Sriharikota',
    source: 'Press Information Bureau',
    date: '22 Aug 2026',
    dateIso: '2026-08-22',
    category: 'SCIENCE_TECH',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Third test of autonomous landing demonstrated 98.7% trajectory accuracy. India becomes the 4th country to achieve powered autonomous landing for orbital-class reusable rockets.',
    topics: ['ISRO', 'RLV', 'Space Technology', 'Indigenous Tech'],
  },
  {
    id: 'news-22-03',
    title: 'Parliament Passes Digital Personal Data Protection (Amendment) Bill 2026',
    source: 'Indian Express',
    date: '22 Aug 2026',
    dateIso: '2026-08-22',
    category: 'POLITY',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'Amendment introduces stricter cross-border data transfer norms, mandatory DPO appointment for companies handling >1 Cr data principals, and empowers Data Protection Board with appellate jurisdiction.',
    topics: ['DPDP Act', 'Data Privacy', 'Digital Rights', 'Legislation'],
  },
  {
    id: 'news-22-04',
    title: 'PM-KISAN Scheme: Government Announces 18th Installment with ₹2,000 Enhanced Benefit',
    source: 'The Hindu',
    date: '22 Aug 2026',
    dateIso: '2026-08-22',
    category: 'AGRICULTURE',
    importance: 'NORMAL',
    gsPaper: 'GS-III',
    summary: 'Enhanced annual income support of ₹8,000 per farmer family approved. Coverage expanded to include landless agricultural workers in 5 pilot states.',
    topics: ['PM-KISAN', 'Agricultural Subsidies', 'Rural Economy'],
  },
  {
    id: 'news-22-05',
    title: 'India Signs Free Trade Agreement with EU After 16 Years of Negotiations',
    source: 'Hindustan Times',
    date: '22 Aug 2026',
    dateIso: '2026-08-22',
    category: 'ECONOMY',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'Comprehensive FTA covers goods, services, and investment. Tariff elimination on 90% of goods over 10 years. Includes sustainability and labor chapters.',
    topics: ['India-EU FTA', 'International Trade', 'WTO'],
  },

  // ─── 21 Aug 2026 ─────────────────────────────────────────
  {
    id: 'news-21-01',
    title: '16th Finance Commission Submits Interim Report on Fiscal Federalism Restructuring',
    source: 'The Hindu',
    date: '21 Aug 2026',
    dateIso: '2026-08-21',
    category: 'POLITY',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'Recommends increasing states\' share in central tax pool to 44%. Proposes performance-linked grants for urban local bodies and district-level governance.',
    topics: ['Finance Commission', 'Fiscal Federalism', 'Tax Devolution'],
  },
  {
    id: 'news-21-02',
    title: 'Chandrayaan-4 Sample Return Mission Approved by Union Cabinet',
    source: 'Press Information Bureau',
    date: '21 Aug 2026',
    dateIso: '2026-08-21',
    category: 'SCIENCE_TECH',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'ISRO to attempt robotic lunar sample return from south polar region. Mission budget ₹6,500 Cr with expected launch in Q4 2028.',
    topics: ['Chandrayaan-4', 'ISRO', 'Lunar Exploration'],
  },
  {
    id: 'news-21-03',
    title: 'India Achieves 200 GW Renewable Energy Installed Capacity Milestone',
    source: 'Indian Express',
    date: '21 Aug 2026',
    dateIso: '2026-08-21',
    category: 'ENVIRONMENT',
    importance: 'NORMAL',
    gsPaper: 'GS-III',
    summary: 'Solar (120 GW) and wind (60 GW) lead the mix. MNRE targets 500 GW non-fossil capacity by 2030 under Paris Agreement commitments.',
    topics: ['Renewable Energy', 'Climate Change', 'Paris Agreement', 'Solar Energy'],
  },
  {
    id: 'news-21-04',
    title: 'NITI Aayog Releases Multidimensional Poverty Index 2026: Poverty Reduced to 8.2%',
    source: 'The Hindu',
    date: '21 Aug 2026',
    dateIso: '2026-08-21',
    category: 'SOCIETY',
    importance: 'NORMAL',
    gsPaper: 'GS-I',
    summary: 'MPI shows 13.5 Cr people exited multidimensional poverty since 2015. Bihar, UP, and MP show maximum improvement. Urban-rural gap narrows.',
    topics: ['MPI', 'Poverty Reduction', 'NITI Aayog', 'SDGs'],
  },
  {
    id: 'news-21-05',
    title: 'INS Arighat: India Commissions Second Nuclear-Powered Ballistic Missile Submarine',
    source: 'Hindustan Times',
    date: '21 Aug 2026',
    dateIso: '2026-08-21',
    category: 'DEFENCE',
    importance: 'HIGH',
    gsPaper: 'GS-III',
    summary: 'INS Arighat strengthens India\'s nuclear triad capability. Equipped with K-4 submarine-launched ballistic missiles with 3,500 km range.',
    topics: ['Nuclear Triad', 'Indian Navy', 'Strategic Defence'],
  },

  // ─── 20 Aug 2026 ─────────────────────────────────────────
  {
    id: 'news-20-01',
    title: 'Election Commission Recommends Simultaneous Elections Framework to Law Ministry',
    source: 'The Hindu',
    date: '20 Aug 2026',
    dateIso: '2026-08-20',
    category: 'POLITY',
    importance: 'NORMAL',
    gsPaper: 'GS-II',
    summary: 'Draft framework proposes phased implementation: Lok Sabha + State Assemblies synchronization by 2029. Requires constitutional amendments to Articles 83, 172, 356.',
    topics: ['One Nation One Election', 'Electoral Reform', 'Constitutional Amendment'],
  },
  {
    id: 'news-20-02',
    title: 'India-Middle East-Europe Economic Corridor (IMEC): First Phase Construction Begins',
    source: 'Indian Express',
    date: '20 Aug 2026',
    dateIso: '2026-08-20',
    category: 'IR',
    importance: 'HIGH',
    gsPaper: 'GS-II',
    summary: 'Port connectivity infrastructure between Mumbai and Haifa initiated. Rail and shipping route to reduce India-Europe goods transit time by 40%.',
    topics: ['IMEC', 'Connectivity', 'Infrastructure', 'Geopolitics'],
  },
  {
    id: 'news-20-03',
    title: 'National Green Tribunal Orders Complete Ban on Single-Use Plastics Near River Floodplains',
    source: 'The Hindu',
    date: '20 Aug 2026',
    dateIso: '2026-08-20',
    category: 'ENVIRONMENT',
    importance: 'NORMAL',
    gsPaper: 'GS-III',
    summary: 'NGT expands plastic-free zones to include all major river floodplains (Ganga, Yamuna, Narmada, Godavari). Local bodies given 6-month compliance deadline.',
    topics: ['NGT', 'Plastic Pollution', 'River Conservation'],
  },
  {
    id: 'news-20-04',
    title: 'Cabinet Approves National Urban Digital Mission for Smart City 2.0 Infrastructure',
    source: 'Press Information Bureau',
    date: '20 Aug 2026',
    dateIso: '2026-08-20',
    category: 'GOVERNANCE',
    importance: 'NORMAL',
    gsPaper: 'GS-II',
    summary: 'NUDM integrates urban governance platforms across 500 cities. Unified digital property registry, water supply monitoring, and citizen grievance redressal.',
    topics: ['Smart Cities', 'Urban Governance', 'E-Governance', 'Digital India'],
  }
];

export function getAvailableNewsDates(): string[] {
  return Array.from(new Set(ALL_NEWS_ITEMS.map((item) => item.dateIso))).sort().reverse();
}
